Invalid HTTP_HOST header: 'fundacionleirion.com'. You may need to add 'fundacionleirion.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/fundacio16/virtualenv/apps/python/main/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/fundacio16/virtualenv/apps/python/main/3.9/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/fundacio16/virtualenv/apps/python/main/3.9/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/fundacio16/virtualenv/apps/python/main/3.9/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'fundacionleirion.com'. You may need to add 'fundacionleirion.com' to ALLOWED_HOSTS.
Bad Request: /
Invalid HTTP_HOST header: 'fundacionleirion.com'. You may need to add 'fundacionleirion.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/fundacio16/virtualenv/apps/python/main/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/fundacio16/virtualenv/apps/python/main/3.9/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/fundacio16/virtualenv/apps/python/main/3.9/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/fundacio16/virtualenv/apps/python/main/3.9/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'fundacionleirion.com'. You may need to add 'fundacionleirion.com' to ALLOWED_HOSTS.
Bad Request: /
Invalid HTTP_HOST header: 'fundacionleirion.com'. You may need to add 'fundacionleirion.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/fundacio16/virtualenv/apps/python/main/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/fundacio16/virtualenv/apps/python/main/3.9/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/fundacio16/virtualenv/apps/python/main/3.9/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/fundacio16/virtualenv/apps/python/main/3.9/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'fundacionleirion.com'. You may need to add 'fundacionleirion.com' to ALLOWED_HOSTS.
Bad Request: /
Invalid HTTP_HOST header: 'fundacionleirion.com'. You may need to add 'fundacionleirion.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/fundacio16/virtualenv/apps/python/main/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/fundacio16/virtualenv/apps/python/main/3.9/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/fundacio16/virtualenv/apps/python/main/3.9/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/fundacio16/virtualenv/apps/python/main/3.9/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'fundacionleirion.com'. You may need to add 'fundacionleirion.com' to ALLOWED_HOSTS.
Bad Request: /
Invalid HTTP_HOST header: 'fundacionleirion.com'. You may need to add 'fundacionleirion.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/fundacio16/virtualenv/apps/python/main/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/fundacio16/virtualenv/apps/python/main/3.9/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/fundacio16/virtualenv/apps/python/main/3.9/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/fundacio16/virtualenv/apps/python/main/3.9/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'fundacionleirion.com'. You may need to add 'fundacionleirion.com' to ALLOWED_HOSTS.
Bad Request: /
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
Not Found: /favicon.ico
Invalid HTTP_HOST header: 'www.fundacionleirion.com'. You may need to add 'www.fundacionleirion.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/fundacio16/virtualenv/apps/python/main/3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/fundacio16/virtualenv/apps/python/main/3.9/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/fundacio16/virtualenv/apps/python/main/3.9/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/fundacio16/virtualenv/apps/python/main/3.9/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.fundacionleirion.com'. You may need to add 'www.fundacionleirion.com' to ALLOWED_HOSTS.
Bad Request: /robots.txt
